### ISSUE TITLE
[ui]There are several places in the actual display and the ui design is unreasonable

### ISSUE THREAD

**Issue by 15168316096** [Daryl-L/ckbstats#15]
There are several places in the actual display and the ui design is unreasonable

**color**

1. avg block time should be blue
![image](https://user-images.githubusercontent.com/45781590/218916535-eb1883c9-a0e1-4591-a894-82671e8498e1.png)

2. Node latency should be yellow when value is 0
![image](https://user-images.githubusercontent.com/45781590/218916739-c604e27c-25ea-47a0-8979-bbf3e2650725.png)

3. total difficulty should be red when value is not 0
![image](https://user-images.githubusercontent.com/45781590/218916860-4c3439ec-9afd-442c-89fb-b0fafd36b429.png)

**typesetting**
1. The position of data and description is reversed
![image](https://user-images.githubusercontent.com/45781590/218916988-133ffebe-1d29-4ca9-a283-d0170c7ef2a2.png)

**Comment by Xcodes-chain** [comment]
**cycle test result**

- _color_ pass

1. avg block time should be blue
2. Node latency should be yellow when value is 0
3. total difficulty should be red when value is not 0
<img width="1591" alt="image" src="https://user-images.githubusercontent.com/45781590/218969792-cd516740-4244-4ca3-ae35-0e6fc020a5bc.png">
