### ISSUE TITLE
[document]wiki update:The node version requires >=12.0.0, otherwise yarn install will fail to install related dependencies, causing the yarn server service to fail to start

### ISSUE THREAD

**Issue by 15168316096** [Daryl-L/ckbstats#8]
script:Wiki update The node version requires >=12.0.0, otherwise yarn install will fail to install related dependencies, causing the yarn server service to fail to start

**Comment by Xcodes-chain** [comment]
**cycle test pass**
use lts version:
![image](https://user-images.githubusercontent.com/45781590/218991245-a9131cea-312e-467d-b99a-3adcdad2069a.png)
