### ISSUE TITLE
[ui vision] Interaction design optimization: The network name field of the node is too long, which will lead to abnormal typesetting interaction

### ISSUE THREAD

**Issue by 15168316096** [Daryl-L/ckbstats#9]
Script：The network name field of the node is too long, which will lead to abnormal typesetting interaction
Content：![image](https://user-images.githubusercontent.com/45781590/211127753-df936d8a-8032-4bdd-9114-5b9385a773a9.png)

**Comment by Xcodes-chain** [comment]
**cycle test：pass**
<img width="1598" alt="image" src="https://user-images.githubusercontent.com/45781590/218983348-554d60a0-a87b-4dbe-858e-4649d8728d9a.png">
